version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo_db}
      MYSQL_USER: ${MYSQL_USER:-todo_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-todo_password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKERHUB_ID:-yourusername}/backend:v1.0.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: todo-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-todo_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-todo_password}
      DB_NAME: ${MYSQL_DATABASE:-todo_db}
    ports:
      - "5000:5000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local