apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todo-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc2VyMTIz  # base64("passer123")
  MYSQL_DATABASE: dG9kb19kYg==       # base64("todo_db")
  MYSQL_USER: dG9kb191c2Vy           # base64("todo_user")
  MYSQL_PASSWORD: dG9kb19wYXNzd29yZA==  # base64("todo_password")
